version: '3.8'

services:
  # Reverse Proxy (entry point)
  reverse-proxy:
    image: ${ACR_NAME}.azurecr.io/habitarium-proxy:${IMAGE_TAG}
    ports:
      - "8080:8080"  # Azure requires this
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - habitarium-network

  backend:
    image: ${ACR_NAME}.azurecr.io/habitarium-backend:${IMAGE_TAG}
    environment:
      - NODE_ENV=production
      - PORT=8080
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI}
      - FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - habitarium-network

  frontend:
    image: ${ACR_NAME}.azurecr.io/habitarium-frontend:${IMAGE_TAG}
    container_name: habitarium-frontend
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_API_URL=https://${AZURE_WEBAPP_NAME}-${STAGING_SLOT}.azurewebsites.net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - habitarium-network

networks:
  habitarium-network:
    driver: bridge
