version: '3.8'

services:
  backend:
    image: ${ACR_NAME}.azurecr.io/habitarium-backend:${IMAGE_TAG}
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      # Add Firebase env vars here or configure them as App Settings in Azure
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI}
      - FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - habitarium-network

  frontend:
    image: ${ACR_NAME}.azurecr.io/habitarium-frontend:${IMAGE_TAG}
    container_name: habitarium-frontend
    ports:
      - "8081:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_API_URL=https://${AZURE_WEBAPP_NAME}-${STAGING_SLOT}.azurewebsites.net
    networks:
      - habitarium-network

networks:
  habitarium-network:
    driver: bridge


# Optional: Add volumes for persistent data if needed
volumes:
  habitarium-data:
    driver: local