project_name          = "habitarium"
environment          = "prod"
region      = "us-central1"
firebase_project_id  = "your-firebase-project-id"
firebase_private_key = "your-firebase-private-key"
firebase_client_email = "your-firebase-client-email"
domain_name          = "" 